name: Build C++ Program

on:
  push:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get install -y build-essential
      - name: Build with Makefile
        run: make

